docs: Update examples for all scenarios
lacework/terraform-aws-cloudtrail pull request #24
Opened 2021-02-17 04:18 UTC by scottford-lw

This PR updates all example scenarios with updated READMEs and links back to Lacework support docs.

Signed-off-by: Scott Ford <scott.ford@lacework.net>

2021-02-18 02:29 UTC, afiune requested changes

2021-02-18 02:29 UTC, afiune commented on examples/complete-cloudtrail/README.md
> +  version = "~> 0.1.3"
```suggestion
  version = "~> 0.1.5"
```

2021-02-18 02:29 UTC, afiune commented on examples/complete-cloudtrail-access-logs/README.md
> +  source = "../../"
The examples inside the README.md should have the actual source and version:
```suggestion
  source  = "lacework/cloudtrail/aws"
  version = "~> 0.1.5"
```

2021-02-18 02:29 UTC, afiune commented on examples/complete-cloudtrail-versioning/README.md
> +  source = "../../"
```suggestion
  source  = "lacework/cloudtrail/aws"
  version = "~> 0.1.5"
```

2021-02-18 02:29 UTC, afiune commented on examples/complete-cloudtrail/main.tf
> +  version = "~> 0.1.3"
These are living tests, we need them to point to the local directory:
```suggestion
  source = "../../"
```

2021-02-18 02:29 UTC, afiune commented on examples/consolidated-cloudtrail-multiple-lacework-tenants/README.md
> +  source = "../../"
```suggestion
  source  = "lacework/cloudtrail/aws"
  version = "~> 0.1.5"
```

2021-02-18 02:29 UTC, afiune commented on examples/consolidated-cloudtrail/README.md
> +  source = "../../"
```suggestion
  source  = "lacework/cloudtrail/aws"
  version = "~> 0.1.5"
```

2021-02-18 02:29 UTC, afiune commented on examples/existing-cloudtrail-iam-role/README.md
> +  source = "../../"
```suggestion
  source  = "lacework/cloudtrail/aws"
  version = "~> 0.1.5"
```

2021-02-18 02:29 UTC, afiune commented on examples/existing-cloudtrail/README.md
> +  source = "../../"
```suggestion
  source  = "lacework/cloudtrail/aws"
  version = "~> 0.1.5"
```

2021-02-18 17:26 UTC, scottford-lw commented
@afiune this should be good to go!

2021-02-18 17:28 UTC, scottford-lw commented
@afiune I spoke too soon. It looks like the `main.tf` cannot have a `required_providers` if we include a `versions.tf`

2021-02-18 17:40 UTC, scottford-lw commented
@afiune this is good to go now.

2021-02-19 14:21 UTC, afiune commented on examples/complete-cloudtrail/README.md
> +provider "aws" {}
```suggestion
provider "aws" {
  region = "us-west-2"
}
```

2021-02-19 14:21 UTC, afiune commented on examples/complete-cloudtrail/main.tf
> +provider "aws" {}
```suggestion
provider "aws" {
  region = "us-west-2"
}
```

2021-02-19 14:22 UTC, afiune commented on examples/complete-cloudtrail/main.tf
> +
```suggestion
```

2021-02-19 14:23 UTC, afiune approved these changes
![tenor-27190589](https://user-images.githubusercontent.com/5712253/108516336-58bd1100-7283-11eb-8a69-ba566ae0673f.gif)

2021-02-19 14:25 UTC, merged